# .gitlab-ci.yml
# Inherits the full shared template from @zairakai/js-dev-tools.

include:
  - project: "zairakai/npm-packages/js-dev-tools"
    ref: v1.2.2
    file: ".gitlab/ci/pipeline-js-package.yml"

variables:
  CACHE_KEY: "vue-components-v1"
  NPM_PACKAGE_NAME: "@zairakai/vue-components"
